from django.urls import path

from . import views


urlpatterns = [
    path("health/", views.health),
    path("csrf/", views.csrf),
    path("auth/me/", views.me),
    path("auth/update-profile/", views.update_profile),
    path("auth/login/", views.login_view),
    path("auth/logout/", views.logout_view),
    path("auth/signup/", views.signup_view),
    path("auth/trainer-signup/", views.trainer_signup_view),
    path("auth/email-verify/", views.email_verify_view),
    path("auth/password-reset/", views.password_reset_request),
    path("auth/password-reset/confirm/", views.password_reset_confirm),
    path("dashboard/", views.dashboard),
    path("programs/", views.program_list),
    path("applications/", views.application_list),
    path("applications/create/", views.application_create),
    path("trainers/", views.available_trainers),
    path("connect/", views.connect_trainer),
    path("connections/", views.my_connections),
    path("connections/<int:connection_id>/approve/", views.connection_approve),
    path("connections/<int:connection_id>/reject/", views.connection_reject),
    path("trainers/<int:trainer_id>/", views.trainer_detail),
    path("select-trainers/", views.select_trainers),
    path("my-trainers/", views.my_trainers),
    path("manage/users/", views.manage_users),
    path("manage/users/<int:user_id>/", views.manage_user_detail),
    path("manage/programs/", views.manage_programs),
    path("manage/programs/<int:program_id>/", views.manage_program_detail),
    path("manage/programs/<int:program_id>/restrict/", views.restrict_program),
    path("manage/programs/<int:program_id>/unrestrict/", views.unrestrict_program),
    path("manage/applications/", views.manage_applications),
    path("manage/applications/<int:application_id>/", views.manage_application_detail),
    path("manage/courses/", views.manage_courses),
    path("manage/courses/<int:course_id>/", views.manage_course_detail),
    path("admin/courses/", views.admin_courses),
    path("manage/courses/<int:course_id>/restrict/", views.restrict_course),
    path("manage/courses/<int:course_id>/unrestrict/", views.unrestrict_course),
    path("manage/fast-track-videos/", views.manage_fast_track_videos),
    path("manage/fast-track-videos/<int:video_id>/", views.manage_fast_track_video_detail),
    path("fast-track-videos/<int:course_id>/", views.fast_track_videos_for_course),
    path("courses/<int:course_id>/", views.course_detail),
    path("trainer/corpers/", views.my_corpers),
    path("trainer/corpers/<int:corper_id>/", views.corper_profile_for_trainer),
    path("trainee/fast-track-courses/", views.trainee_fast_track_courses),
    path("dunis/pending-payments/", views.dunis_pending_payments),
    path("dunis/confirm-payment/", views.dunis_confirm_payment),
    path("dunis/trainers/", views.dunis_all_trainers),
    path("dunis/toggle-fast-track/<int:user_id>/", views.dunis_toggle_fast_track),
    path("manage/fetch-video-duration/", views.fetch_video_duration),
    path("paystack/initialize/", views.paystack_initialize),
    path("courses/pay/", views.course_pay_initialize),
    path("courses/pay/verify/", views.course_pay_verify),
    path("courses/<int:course_id>/enrollment-status/", views.course_enrollment_status),
    path("trainer/enrollments/pending/", views.trainer_pending_enrollments),
    path("trainer/enrollments/<int:enrollment_id>/confirm/", views.trainer_confirm_enrollment),
    path("trainer/enrollments/<int:enrollment_id>/reject/", views.trainer_reject_enrollment),
    path("admin/refunds/pending/", views.admin_pending_refunds),
    path("admin/refunds/<int:enrollment_id>/process/", views.admin_process_refund),
    path("admin/refunds/<int:enrollment_id>/reject/", views.admin_reject_refund),
    path("notifications/", views.notification_list),
    path("notifications/read-all/", views.notification_mark_all_read),
    path("notifications/<int:notification_id>/read/", views.notification_mark_read),
    path("submit-complaint/", views.submit_complaint),
]
