# Generated by Django 5.2.1 on 2026-06-03 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('agriculture', 'Agriculture'), ('business', 'Business'), ('creative', 'Creative'), ('vocational', 'Vocational')], max_length=32)),
                ('description', models.TextField()),
                ('duration_weeks', models.PositiveSmallIntegerField(default=4)),
                ('capacity', models.PositiveIntegerField(default=40)),
                ('trainer_name', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('corps_member', 'Corps Member'), ('trainer', 'Trainer'), ('admin', 'Admin')], default='corps_member', max_length=24)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('nysc_state_code', models.CharField(blank=True, max_length=32)),
                ('state_of_deployment', models.CharField(blank=True, max_length=80)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('declined', 'Declined')], default='pending', max_length=16)),
                ('motivation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saed.program')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('applicant', 'program')},
            },
        ),
    ]
