# Generated by Django 6.0.4 on 2026-06-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('agro_allied', 'Agro Allied'), ('automobile', 'Automobile'), ('beautification', 'Beautification'), ('construction', 'Construction'), ('cosmetology', 'Cosmetology'), ('culture_tourism', 'Culture & Tourism'), ('education', 'Education'), ('environment', 'Environment'), ('film_photography', 'Film & Photography'), ('food_processing', 'Food Processing/Preservation'), ('ict', 'ICT'), ('power_energy', 'Power & Energy')], max_length=32),
        ),
    ]
