# Generated by Django 6.0.4 on 2026-06-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saed', '0003_program_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='authorized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
