# Generated by Django 6.0.4 on 2026-06-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saed', '0004_profile_authorized_at_profile_has_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lga_of_deployment',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='profile',
            name='state_of_origin',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
