# Generated by Django 6.0.4 on 2026-06-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saed', '0006_profile_bio_profile_company_name_profile_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_selected_trainers',
            field=models.BooleanField(default=False),
        ),
    ]
