# Generated by Django 6.0.4 on 2026-06-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saed', '0007_profile_has_selected_trainers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='authorization_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('removed', 'Removed')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_upload_fast_track',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_busy_corper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
