# Generated by Django 6.0.4 on 2026-06-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saed', '0008_profile_authorization_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('corps_member', 'Corps Member'), ('trainer', 'Trainer'), ('admin', 'SAED Admin'), ('dunis_admin', 'Dunis Admin')], default='corps_member', max_length=24),
        ),
    ]
