# Generated by Django 6.0.4 on 2026-06-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saed', '0010_program_is_restricted_program_restricted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
