# Generated by Django 6.0.4 on 2026-06-17 18:00

from django.db import migrations, models


def rename_admin_role(apps, schema_editor):
    Profile = apps.get_model("saed", "Profile")
    Profile.objects.filter(role="admin").update(role="saed_admin")


class Migration(migrations.Migration):

    dependencies = [
        ('saed', '0013_complaint_model'),
    ]

    operations = [
        migrations.RunPython(rename_admin_role, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='notification',
            name='reason',
            field=models.CharField(choices=[('program_restricted', 'Program Restricted'), ('program_unrestricted', 'Program Unrestricted'), ('connection_request', 'Connection Request'), ('connection_approved', 'Connection Approved'), ('admin_update', 'Admin Update')], default='program_restricted', max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('corps_member', 'Corps Member'), ('trainer', 'Trainer'), ('saed_admin', 'SAED Admin'), ('dunis_admin', 'Dunis Admin')], default='corps_member', max_length=24),
        ),
    ]
