# Generated by Django 6.0.4 on 2026-06-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saed', '0016_course_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_by_role',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
