# Generated by Django 6.0.4 on 2026-06-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saed', '0017_add_notification_created_by_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skill_interests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
