# Generated by Django 6.0.4 on 2026-06-19 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saed', '0018_add_skill_interests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='reason',
            field=models.CharField(choices=[('program_restricted', 'Program Restricted'), ('program_unrestricted', 'Program Unrestricted'), ('course_restricted', 'Course Restricted'), ('course_unrestricted', 'Course Unrestricted'), ('connection_request', 'Connection Request'), ('connection_approved', 'Connection Approved'), ('admin_update', 'Admin Update'), ('user_update', 'User Update')], default='program_restricted', max_length=32),
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference', models.CharField(blank=True, default='', max_length=100)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='saed.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
