# Generated by Django 6.0.4 on 2026-06-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saed', '0020_enrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='refund_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='refund_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='refund_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='refund_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='refund_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='pending', max_length=16),
        ),
    ]
