# Generated by Django 6.0.4 on 2026-06-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saed', '0021_enrollment_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, choices=[('creative_industry', 'Creative Industry'), ('automobile', 'Automobile'), ('construction', 'Construction'), ('agro_allied', 'Agro-Allied'), ('delivery_logistics', 'Delivery & Logistics'), ('culinary_catering', 'Culinary & Catering'), ('cleaning_services', 'Cleaning Services'), ('green_energy_satellite_security', 'Green Energy & Satellite Security'), ('ict', 'ICT'), ('cosmetology', 'Cosmetology'), ('education', 'Education')], max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialization',
            field=models.CharField(blank=True, choices=[('creative_industry', 'Creative Industry'), ('automobile', 'Automobile'), ('construction', 'Construction'), ('agro_allied', 'Agro-Allied'), ('delivery_logistics', 'Delivery & Logistics'), ('culinary_catering', 'Culinary & Catering'), ('cleaning_services', 'Cleaning Services'), ('green_energy_satellite_security', 'Green Energy & Satellite Security'), ('ict', 'ICT'), ('cosmetology', 'Cosmetology'), ('education', 'Education')], max_length=120),
        ),
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('creative_industry', 'Creative Industry'), ('automobile', 'Automobile'), ('construction', 'Construction'), ('agro_allied', 'Agro-Allied'), ('delivery_logistics', 'Delivery & Logistics'), ('culinary_catering', 'Culinary & Catering'), ('cleaning_services', 'Cleaning Services'), ('green_energy_satellite_security', 'Green Energy & Satellite Security'), ('ict', 'ICT'), ('cosmetology', 'Cosmetology'), ('education', 'Education')], max_length=32),
        ),
    ]
