# Generated by Django 6.0.4 on 2026-07-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saed', '0024_add_profile_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_reset_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
