# Generated by Django 6.0.4 on 2026-09-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saed', '0028_program_end_date_program_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.CharField(blank=True, default='Lagos', max_length=120),
        ),
    ]
