# Generated by Django 6.0.4 on 2026-09-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saed', '0029_course_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='restricted_by',
        ),
        migrations.RemoveField(
            model_name='program',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='program',
        ),
        migrations.AlterField(
            model_name='notification',
            name='reason',
            field=models.CharField(choices=[('course_restricted', 'Course Restricted'), ('course_unrestricted', 'Course Unrestricted'), ('connection_request', 'Connection Request'), ('connection_approved', 'Connection Approved'), ('connection_declined', 'Connection Declined'), ('admin_update', 'Admin Update'), ('user_update', 'User Update')], default='course_restricted', max_length=32),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
