# Generated by Django 6.0.4 on 2026-09-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saed', '0030_remove_deprecated_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verification_code_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='reason',
            field=models.CharField(choices=[('course_restricted', 'Course Restricted'), ('course_unrestricted', 'Course Unrestricted'), ('connection_request', 'Connection Request'), ('connection_approved', 'Connection Approved'), ('admin_update', 'Admin Update'), ('user_update', 'User Update')], default='course_restricted', max_length=32),
        ),
    ]
