# Generated by Django 6.0.4 on 2026-09-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saed', '0033_lesson_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='attachment_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
